### ISSUE TITLE
Is it updating for DF?

### ISSUE THREAD

**Issue by Deznait** [geheur/EncounterJournalLootSpecIcons#2]
Hi!

I like this addon, it let's me see easily the drops of each boss without having to change the loot filtering every time (on DK, one hand weapons only drop for Frost, and tank trinkets only drop for Blood)

Will you update it for DF? It doesn't show any errors, but it does nothing on the adventure guide.

**Comment by geheur** [comment]
I have updated it today.
Apparently I didn't have notifications on this repo, so I didn't see this issue.
